# This is a basic workflow to help you get started with Actions

name: Sync To Gitee

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:MafuLiowo/Signal-blocker.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:ma-fu-li/Signal-blocker.git
